#spring.application.name=lsmanutencoes
spring.datasource.url=jdbc:postgresql://ep-green-math-a8m319a5-pooler.eastus2.azure.neon.tech/ls_manutencoes?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TUWum4V7hKaD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format.sql=true

